type AboutMe {
  data: [AboutMeItem]
  meta: Metadata
}

input AboutMeFilter {
  id_eq: Int
  id_neq: Int
  id_lt: Int
  id_lte: Int
  id_gt: Int
  id_gte: Int
  id_in: String
  id_nin: String
  id_between: String
  id_nbetween: String
  created_on_eq: Datetime
  created_on_neq: Datetime
  created_on_lt: Datetime
  created_on_lte: Datetime
  created_on_gt: Datetime
  created_on_gte: Datetime
  created_on_in: Datetime
  created_on_nin: Datetime
  created_on_between: String
  created_on_nbetween: String
  full_name_eq: String
  full_name_neq: String
  full_name_contains: String
  full_name_ncontains: String
  full_name_rlike: String
  full_name_nrlike: String
  full_name_empty: String
  full_name_nempty: String
  full_name_null: String
  full_name_nnull: String
  picture_all: String
  picture_has: String
  descriptions_all: String
  descriptions_has: String
  quote_eq: String
  quote_neq: String
  quote_contains: String
  quote_ncontains: String
  quote_rlike: String
  quote_nrlike: String
  quote_empty: String
  quote_nempty: String
  quote_null: String
  quote_nnull: String
  or: [AboutMeFilter]
  and: [AboutMeFilter]
}

type AboutMeItem {
  id: ID!
  created_on: Datetime
  full_name: String!
  picture: DirectusFileItem!
  descriptions: JSON
  quote: String
}

type Carousel {
  data: [CarouselItem]
  meta: Metadata
}

input CarouselFilter {
  id_eq: Int
  id_neq: Int
  id_lt: Int
  id_lte: Int
  id_gt: Int
  id_gte: Int
  id_in: String
  id_nin: String
  id_between: String
  id_nbetween: String
  status_eq: String
  status_neq: String
  status_in: String
  status_nin: String
  image_all: String
  image_has: String
  title_eq: String
  title_neq: String
  title_contains: String
  title_ncontains: String
  title_rlike: String
  title_nrlike: String
  title_empty: String
  title_nempty: String
  title_null: String
  title_nnull: String
  description_eq: String
  description_neq: String
  description_contains: String
  description_ncontains: String
  description_rlike: String
  description_nrlike: String
  description_empty: String
  description_nempty: String
  description_null: String
  description_nnull: String
  or: [CarouselFilter]
  and: [CarouselFilter]
}

type CarouselItem {
  id: ID!
  status: String!
  image: DirectusFileItem!
  title: String
  description: String
}

type Contact {
  data: [ContactItem]
  meta: Metadata
}

input ContactFilter {
  id_eq: Int
  id_neq: Int
  id_lt: Int
  id_lte: Int
  id_gt: Int
  id_gte: Int
  id_in: String
  id_nin: String
  id_between: String
  id_nbetween: String
  created_on_eq: Datetime
  created_on_neq: Datetime
  created_on_lt: Datetime
  created_on_lte: Datetime
  created_on_gt: Datetime
  created_on_gte: Datetime
  created_on_in: Datetime
  created_on_nin: Datetime
  created_on_between: String
  created_on_nbetween: String
  info_eq: String
  info_neq: String
  info_contains: String
  info_ncontains: String
  info_rlike: String
  info_nrlike: String
  info_empty: String
  info_nempty: String
  info_null: String
  info_nnull: String
  icon_eq: String
  icon_neq: String
  icon_contains: String
  icon_ncontains: String
  icon_rlike: String
  icon_nrlike: String
  icon_empty: String
  icon_nempty: String
  icon_null: String
  icon_nnull: String
  or: [ContactFilter]
  and: [ContactFilter]
}

type ContactItem {
  id: ID!
  created_on: Datetime
  info: String!
  icon: String!
}

"""Datetime scalar type."""
scalar Datetime

type DirectusActivity {
  data: [DirectusActivityItem]
  meta: Metadata
}

input DirectusActivityFilter {
  id_eq: Int
  id_neq: Int
  id_lt: Int
  id_lte: Int
  id_gt: Int
  id_gte: Int
  id_in: String
  id_nin: String
  id_between: String
  id_nbetween: String
  action_eq: String
  action_neq: String
  action_contains: String
  action_ncontains: String
  action_rlike: String
  action_nrlike: String
  action_empty: String
  action_nempty: String
  action_null: String
  action_nnull: String
  action_by_eq: Int
  action_by_neq: Int
  action_by_lt: Int
  action_by_lte: Int
  action_by_gt: Int
  action_by_gte: Int
  action_by_in: String
  action_by_nin: String
  action_by_between: String
  action_by_nbetween: String
  action_on_eq: Datetime
  action_on_neq: Datetime
  action_on_lt: Datetime
  action_on_lte: Datetime
  action_on_gt: Datetime
  action_on_gte: Datetime
  action_on_in: Datetime
  action_on_nin: Datetime
  action_on_between: String
  action_on_nbetween: String
  ip_eq: String
  ip_neq: String
  ip_contains: String
  ip_ncontains: String
  ip_rlike: String
  ip_nrlike: String
  ip_empty: String
  ip_nempty: String
  ip_null: String
  ip_nnull: String
  user_agent_eq: String
  user_agent_neq: String
  user_agent_contains: String
  user_agent_ncontains: String
  user_agent_rlike: String
  user_agent_nrlike: String
  user_agent_empty: String
  user_agent_nempty: String
  user_agent_null: String
  user_agent_nnull: String
  collection_eq: String
  collection_neq: String
  collection_contains: String
  collection_ncontains: String
  collection_rlike: String
  collection_nrlike: String
  collection_empty: String
  collection_nempty: String
  collection_null: String
  collection_nnull: String
  item_eq: String
  item_neq: String
  item_contains: String
  item_ncontains: String
  item_rlike: String
  item_nrlike: String
  item_empty: String
  item_nempty: String
  item_null: String
  item_nnull: String
  edited_on_eq: Datetime
  edited_on_neq: Datetime
  edited_on_lt: Datetime
  edited_on_lte: Datetime
  edited_on_gt: Datetime
  edited_on_gte: Datetime
  edited_on_in: Datetime
  edited_on_nin: Datetime
  edited_on_between: String
  edited_on_nbetween: String
  comment_eq: String
  comment_neq: String
  comment_contains: String
  comment_ncontains: String
  comment_rlike: String
  comment_nrlike: String
  comment_empty: String
  comment_nempty: String
  comment_null: String
  comment_nnull: String
  comment_deleted_on_eq: Datetime
  comment_deleted_on_neq: Datetime
  comment_deleted_on_lt: Datetime
  comment_deleted_on_lte: Datetime
  comment_deleted_on_gt: Datetime
  comment_deleted_on_gte: Datetime
  comment_deleted_on_in: Datetime
  comment_deleted_on_nin: Datetime
  comment_deleted_on_between: String
  comment_deleted_on_nbetween: String
  or: [DirectusActivityFilter]
  and: [DirectusActivityFilter]
}

type DirectusActivityItem {
  id: ID
  action: String
  collection: String
  item: String
  action_by: DirectusUserItem
  action_on: Datetime
  edited_on: Datetime
  comment_deleted_on: Datetime
  ip: String
  user_agent: String
  comment: String
}

type DirectusCollection {
  data: [DirectusCollectionItem]
  meta: Metadata
}

type DirectusCollectionItem {
  collection: String
  fields: [DirectusFieldItem]
  note: String
  managed: Boolean
  hidden: Boolean
  single: Boolean
  translation: String
  icon: String
}

type DirectusCollectionPreset {
  data: [DirectusCollectionPresetItem]
  meta: Metadata
}

type DirectusCollectionPresetItem {
  id: ID
  title: String
  user: Int
  role: Int
  collection: String
  search_query: String
  filters: JSON
  view_options: JSON
  view_type: String
  view_query: JSON
  translation: String
}

input DirectusCollectionPresetsFilter {
  id_eq: Int
  id_neq: Int
  id_lt: Int
  id_lte: Int
  id_gt: Int
  id_gte: Int
  id_in: String
  id_nin: String
  id_between: String
  id_nbetween: String
  title_eq: String
  title_neq: String
  title_contains: String
  title_ncontains: String
  title_rlike: String
  title_nrlike: String
  title_empty: String
  title_nempty: String
  title_null: String
  title_nnull: String
  user_eq: Int
  user_neq: Int
  user_lt: Int
  user_lte: Int
  user_gt: Int
  user_gte: Int
  user_in: String
  user_nin: String
  user_between: String
  user_nbetween: String
  role_eq: Int
  role_neq: Int
  role_in: String
  role_nin: String
  role_contains: String
  role_ncontains: String
  role_rlike: String
  role_nrlike: String
  collection_eq: Int
  collection_neq: Int
  collection_in: String
  collection_nin: String
  collection_contains: String
  collection_ncontains: String
  collection_rlike: String
  collection_nrlike: String
  search_query_eq: String
  search_query_neq: String
  search_query_contains: String
  search_query_ncontains: String
  search_query_rlike: String
  search_query_nrlike: String
  search_query_empty: String
  search_query_nempty: String
  search_query_null: String
  search_query_nnull: String
  filters_all: String
  filters_has: String
  view_type_eq: String
  view_type_neq: String
  view_type_contains: String
  view_type_ncontains: String
  view_type_rlike: String
  view_type_nrlike: String
  view_type_empty: String
  view_type_nempty: String
  view_type_null: String
  view_type_nnull: String
  view_query_all: String
  view_query_has: String
  view_options_all: String
  view_options_has: String
  translation_eq: String
  translation_neq: String
  translation_contains: String
  translation_ncontains: String
  translation_rlike: String
  translation_nrlike: String
  translation_empty: String
  translation_nempty: String
  translation_null: String
  translation_nnull: String
  or: [DirectusCollectionPresetsFilter]
  and: [DirectusCollectionPresetsFilter]
}

type DirectusField {
  data: [DirectusFieldItem]
  meta: Metadata
}

type DirectusFieldItem {
  collection: DirectusCollectionItem
  field: String
  type: String
  interface: String
  options: JSON
  locked: Boolean
  translation: JSON
  readonly: Boolean
  required: Boolean
  sort: Int
  width: Int
  validation: String
  storage: Int
  hidden_browse: Int
  url: String
}

type DirectusFile {
  data: [DirectusFileItem]
  meta: Metadata
}

type DirectusFileItem {
  id: ID
  filename_disk: String
  title: String
  description: String
  location: String
  tags: [String]
  width: Int
  height: Int
  filesize: Int
  duration: String
  metadata: String
  type: String
  charset: String
  embed: String
  storage: String
  full_url: String
  url: String
  thumbnails: [DirectusFileThumbnailItem]
  uploaded_on: Datetime
  uploaded_by: DirectusUserItem
  checksum: String
}

input DirectusFilesFilter {
  id_eq: Int
  id_neq: Int
  id_lt: Int
  id_lte: Int
  id_gt: Int
  id_gte: Int
  id_in: String
  id_nin: String
  id_between: String
  id_nbetween: String
  storage_eq: String
  storage_neq: String
  storage_contains: String
  storage_ncontains: String
  storage_rlike: String
  storage_nrlike: String
  storage_empty: String
  storage_nempty: String
  storage_null: String
  storage_nnull: String
  private_hash_eq: String
  private_hash_neq: String
  private_hash_contains: String
  private_hash_ncontains: String
  private_hash_rlike: String
  private_hash_nrlike: String
  private_hash_empty: String
  private_hash_nempty: String
  private_hash_null: String
  private_hash_nnull: String
  filename_disk_eq: String
  filename_disk_neq: String
  filename_disk_contains: String
  filename_disk_ncontains: String
  filename_disk_rlike: String
  filename_disk_nrlike: String
  filename_disk_empty: String
  filename_disk_nempty: String
  filename_disk_null: String
  filename_disk_nnull: String
  filename_download_eq: String
  filename_download_neq: String
  filename_download_contains: String
  filename_download_ncontains: String
  filename_download_rlike: String
  filename_download_nrlike: String
  filename_download_empty: String
  filename_download_nempty: String
  filename_download_null: String
  filename_download_nnull: String
  title_eq: String
  title_neq: String
  title_contains: String
  title_ncontains: String
  title_rlike: String
  title_nrlike: String
  title_empty: String
  title_nempty: String
  title_null: String
  title_nnull: String
  type_eq: String
  type_neq: String
  type_contains: String
  type_ncontains: String
  type_rlike: String
  type_nrlike: String
  type_empty: String
  type_nempty: String
  type_null: String
  type_nnull: String
  uploaded_by_eq: Int
  uploaded_by_neq: Int
  uploaded_by_in: String
  uploaded_by_nin: String
  uploaded_on_eq: Datetime
  uploaded_on_neq: Datetime
  uploaded_on_lt: Datetime
  uploaded_on_lte: Datetime
  uploaded_on_gt: Datetime
  uploaded_on_gte: Datetime
  uploaded_on_in: Datetime
  uploaded_on_nin: Datetime
  uploaded_on_between: String
  uploaded_on_nbetween: String
  charset_eq: String
  charset_neq: String
  charset_contains: String
  charset_ncontains: String
  charset_rlike: String
  charset_nrlike: String
  charset_empty: String
  charset_nempty: String
  charset_null: String
  charset_nnull: String
  filesize_eq: Int
  filesize_neq: Int
  filesize_lt: Int
  filesize_lte: Int
  filesize_gt: Int
  filesize_gte: Int
  filesize_in: String
  filesize_nin: String
  filesize_between: String
  filesize_nbetween: String
  width_eq: Int
  width_neq: Int
  width_lt: Int
  width_lte: Int
  width_gt: Int
  width_gte: Int
  width_in: String
  width_nin: String
  width_between: String
  width_nbetween: String
  height_eq: Int
  height_neq: Int
  height_lt: Int
  height_lte: Int
  height_gt: Int
  height_gte: Int
  height_in: String
  height_nin: String
  height_between: String
  height_nbetween: String
  duration_eq: Int
  duration_neq: Int
  duration_lt: Int
  duration_lte: Int
  duration_gt: Int
  duration_gte: Int
  duration_in: String
  duration_nin: String
  duration_between: String
  duration_nbetween: String
  embed_eq: String
  embed_neq: String
  embed_contains: String
  embed_ncontains: String
  embed_rlike: String
  embed_nrlike: String
  embed_empty: String
  embed_nempty: String
  embed_null: String
  embed_nnull: String
  folder_eq: Int
  folder_neq: Int
  folder_in: String
  folder_nin: String
  folder_contains: String
  folder_ncontains: String
  folder_rlike: String
  folder_nrlike: String
  description_eq: String
  description_neq: String
  description_contains: String
  description_ncontains: String
  description_rlike: String
  description_nrlike: String
  description_empty: String
  description_nempty: String
  description_null: String
  description_nnull: String
  location_eq: String
  location_neq: String
  location_contains: String
  location_ncontains: String
  location_rlike: String
  location_nrlike: String
  location_empty: String
  location_nempty: String
  location_null: String
  location_nnull: String
  tags_all: String
  tags_has: String
  checksum_eq: String
  checksum_neq: String
  checksum_contains: String
  checksum_ncontains: String
  checksum_rlike: String
  checksum_nrlike: String
  checksum_empty: String
  checksum_nempty: String
  checksum_null: String
  checksum_nnull: String
  metadata_all: String
  metadata_has: String
  data_all: String
  data_has: String
  preview_all: String
  preview_has: String
  or: [DirectusFilesFilter]
  and: [DirectusFilesFilter]
}

type DirectusFileThumbnailItem {
  url: String
  relative_url: String
  dimension: String
  width: Int
  height: Int
}

type DirectusFolder {
  data: [DirectusFolderItem]
  meta: Metadata
}

type DirectusFolderItem {
  id: ID
  name: String
  parent_folder: String
}

input DirectusFoldersFilter {
  id_eq: Int
  id_neq: Int
  id_lt: Int
  id_lte: Int
  id_gt: Int
  id_gte: Int
  id_in: String
  id_nin: String
  id_between: String
  id_nbetween: String
  name_eq: String
  name_neq: String
  name_contains: String
  name_ncontains: String
  name_rlike: String
  name_nrlike: String
  name_empty: String
  name_nempty: String
  name_null: String
  name_nnull: String
  parent_folder_eq: Int
  parent_folder_neq: Int
  parent_folder_in: String
  parent_folder_nin: String
  parent_folder_contains: String
  parent_folder_ncontains: String
  parent_folder_rlike: String
  parent_folder_nrlike: String
  or: [DirectusFoldersFilter]
  and: [DirectusFoldersFilter]
}

type DirectusPermission {
  data: [DirectusPermissionItem]
  meta: Metadata
}

type DirectusPermissionItem {
  id: ID
  collection: String
  role: Int
  status: String
  create: String
  read: String
  update: String
  delete: String
  comment: String
  explain: String
  status_blacklist: [String]
  read_field_blacklist: [String]
  write_field_blacklist: [String]
}

input DirectusPermissionsFilter {
  id_eq: Int
  id_neq: Int
  id_lt: Int
  id_lte: Int
  id_gt: Int
  id_gte: Int
  id_in: String
  id_nin: String
  id_between: String
  id_nbetween: String
  collection_eq: Int
  collection_neq: Int
  collection_in: String
  collection_nin: String
  collection_contains: String
  collection_ncontains: String
  collection_rlike: String
  collection_nrlike: String
  role_eq: Int
  role_neq: Int
  role_in: String
  role_nin: String
  role_contains: String
  role_ncontains: String
  role_rlike: String
  role_nrlike: String
  status_eq: String
  status_neq: String
  status_contains: String
  status_ncontains: String
  status_rlike: String
  status_nrlike: String
  status_empty: String
  status_nempty: String
  status_null: String
  status_nnull: String
  create_eq: String
  create_neq: String
  create_contains: String
  create_ncontains: String
  create_rlike: String
  create_nrlike: String
  create_empty: String
  create_nempty: String
  create_null: String
  create_nnull: String
  read_eq: String
  read_neq: String
  read_contains: String
  read_ncontains: String
  read_rlike: String
  read_nrlike: String
  read_empty: String
  read_nempty: String
  read_null: String
  read_nnull: String
  update_eq: String
  update_neq: String
  update_contains: String
  update_ncontains: String
  update_rlike: String
  update_nrlike: String
  update_empty: String
  update_nempty: String
  update_null: String
  update_nnull: String
  delete_eq: String
  delete_neq: String
  delete_contains: String
  delete_ncontains: String
  delete_rlike: String
  delete_nrlike: String
  delete_empty: String
  delete_nempty: String
  delete_null: String
  delete_nnull: String
  comment_eq: String
  comment_neq: String
  comment_contains: String
  comment_ncontains: String
  comment_rlike: String
  comment_nrlike: String
  comment_empty: String
  comment_nempty: String
  comment_null: String
  comment_nnull: String
  explain_eq: String
  explain_neq: String
  explain_contains: String
  explain_ncontains: String
  explain_rlike: String
  explain_nrlike: String
  explain_empty: String
  explain_nempty: String
  explain_null: String
  explain_nnull: String
  read_field_blacklist_all: String
  read_field_blacklist_has: String
  write_field_blacklist_all: String
  write_field_blacklist_has: String
  status_blacklist_all: String
  status_blacklist_has: String
  or: [DirectusPermissionsFilter]
  and: [DirectusPermissionsFilter]
}

type DirectusRelation {
  data: [DirectusRelationItem]
  meta: Metadata
}

type DirectusRelationItem {
  id: ID
  collection_many: String
  field_many: String
  collection_one: String
  field_one: String
  junction_field: String
}

type DirectusRevision {
  data: [DirectusRevisionItem]
  meta: Metadata
}

type DirectusRevisionItem {
  id: ID
  activity: DirectusActivityItem
  collection: String
  item: String
  data: JSON
  delta: JSON
  parent_item: String
  parent_collection: String
  parent_changed: Boolean
}

type DirectusRole {
  data: [DirectusRoleItem]
  meta: Metadata
}

type DirectusRoleItem {
  id: ID
  external_id: String
  name: String
  description: String
  ip_whitelist: String
  nav_blacklist: Boolean
  users: [DirectusUserItem]
}

type DirectusSetting {
  data: [DirectusSettingItem]
  meta: Metadata
}

type DirectusSettingItem {
  id: ID
  key: String
  value: String
}

type DirectusUser {
  data: [DirectusUserItem]
  meta: Metadata
}

type DirectusUserItem {
  id: ID
  status: String
  first_name: String
  last_name: String
  email: String
  email_notifications: Boolean
  company: String
  title: String
  locale: String
  high_contrast_mode: Boolean
  locale_options: String
  timezone: String
  last_access_on: Datetime
  last_page: String
  token: String
  external_id: String
  avatar: DirectusFileItem
  roles: [DirectusRoleItem]
}

input DirectusUsersFilter {
  id_eq: Int
  id_neq: Int
  id_lt: Int
  id_lte: Int
  id_gt: Int
  id_gte: Int
  id_in: String
  id_nin: String
  id_between: String
  id_nbetween: String
  status_eq: String
  status_neq: String
  status_in: String
  status_nin: String
  role_eq: Int
  role_neq: Int
  role_in: String
  role_nin: String
  role_contains: String
  role_ncontains: String
  role_rlike: String
  role_nrlike: String
  first_name_eq: String
  first_name_neq: String
  first_name_contains: String
  first_name_ncontains: String
  first_name_rlike: String
  first_name_nrlike: String
  first_name_empty: String
  first_name_nempty: String
  first_name_null: String
  first_name_nnull: String
  last_name_eq: String
  last_name_neq: String
  last_name_contains: String
  last_name_ncontains: String
  last_name_rlike: String
  last_name_nrlike: String
  last_name_empty: String
  last_name_nempty: String
  last_name_null: String
  last_name_nnull: String
  email_eq: String
  email_neq: String
  email_contains: String
  email_ncontains: String
  email_rlike: String
  email_nrlike: String
  email_empty: String
  email_nempty: String
  email_null: String
  email_nnull: String
  password_all: String
  password_has: String
  token_eq: String
  token_neq: String
  token_contains: String
  token_ncontains: String
  token_rlike: String
  token_nrlike: String
  token_empty: String
  token_nempty: String
  token_null: String
  token_nnull: String
  timezone_eq: String
  timezone_neq: String
  timezone_contains: String
  timezone_ncontains: String
  timezone_rlike: String
  timezone_nrlike: String
  timezone_empty: String
  timezone_nempty: String
  timezone_null: String
  timezone_nnull: String
  locale_eq: String
  locale_neq: String
  locale_contains: String
  locale_ncontains: String
  locale_rlike: String
  locale_nrlike: String
  locale_empty: String
  locale_nempty: String
  locale_null: String
  locale_nnull: String
  locale_options_all: String
  locale_options_has: String
  avatar_all: String
  avatar_has: String
  company_eq: String
  company_neq: String
  company_contains: String
  company_ncontains: String
  company_rlike: String
  company_nrlike: String
  company_empty: String
  company_nempty: String
  company_null: String
  company_nnull: String
  title_eq: String
  title_neq: String
  title_contains: String
  title_ncontains: String
  title_rlike: String
  title_nrlike: String
  title_empty: String
  title_nempty: String
  title_null: String
  title_nnull: String
  email_notifications_eq: Boolean
  last_access_on_eq: Datetime
  last_access_on_neq: Datetime
  last_access_on_lt: Datetime
  last_access_on_lte: Datetime
  last_access_on_gt: Datetime
  last_access_on_gte: Datetime
  last_access_on_in: Datetime
  last_access_on_nin: Datetime
  last_access_on_between: String
  last_access_on_nbetween: String
  last_page_eq: String
  last_page_neq: String
  last_page_contains: String
  last_page_ncontains: String
  last_page_rlike: String
  last_page_nrlike: String
  last_page_empty: String
  last_page_nempty: String
  last_page_null: String
  last_page_nnull: String
  external_id_eq: String
  external_id_neq: String
  external_id_contains: String
  external_id_ncontains: String
  external_id_rlike: String
  external_id_nrlike: String
  external_id_empty: String
  external_id_nempty: String
  external_id_null: String
  external_id_nnull: String
  theme_eq: String
  theme_neq: String
  theme_contains: String
  theme_ncontains: String
  theme_rlike: String
  theme_nrlike: String
  theme_empty: String
  theme_nempty: String
  theme_null: String
  theme_nnull: String
  fa_secret_eq: String
  fa_secret_neq: String
  fa_secret_contains: String
  fa_secret_ncontains: String
  fa_secret_rlike: String
  fa_secret_nrlike: String
  fa_secret_empty: String
  fa_secret_nempty: String
  fa_secret_null: String
  fa_secret_nnull: String
  password_reset_token_eq: String
  password_reset_token_neq: String
  password_reset_token_contains: String
  password_reset_token_ncontains: String
  password_reset_token_rlike: String
  password_reset_token_nrlike: String
  password_reset_token_empty: String
  password_reset_token_nempty: String
  password_reset_token_null: String
  password_reset_token_nnull: String
  or: [DirectusUsersFilter]
  and: [DirectusUsersFilter]
}

type Experience {
  data: [ExperienceItem]
  meta: Metadata
}

input ExperienceFilter {
  id_eq: Int
  id_neq: Int
  id_lt: Int
  id_lte: Int
  id_gt: Int
  id_gte: Int
  id_in: String
  id_nin: String
  id_between: String
  id_nbetween: String
  company_name_eq: String
  company_name_neq: String
  company_name_contains: String
  company_name_ncontains: String
  company_name_rlike: String
  company_name_nrlike: String
  company_name_empty: String
  company_name_nempty: String
  company_name_null: String
  company_name_nnull: String
  company_logo_all: String
  company_logo_has: String
  position_eq: String
  position_neq: String
  position_contains: String
  position_ncontains: String
  position_rlike: String
  position_nrlike: String
  position_empty: String
  position_nempty: String
  position_null: String
  position_nnull: String
  description_eq: String
  description_neq: String
  description_contains: String
  description_ncontains: String
  description_rlike: String
  description_nrlike: String
  description_empty: String
  description_nempty: String
  description_null: String
  description_nnull: String
  website_eq: String
  website_neq: String
  website_contains: String
  website_ncontains: String
  website_rlike: String
  website_nrlike: String
  website_empty: String
  website_nempty: String
  website_null: String
  website_nnull: String
  working_time_eq: String
  working_time_neq: String
  working_time_contains: String
  working_time_ncontains: String
  working_time_rlike: String
  working_time_nrlike: String
  working_time_empty: String
  working_time_nempty: String
  working_time_null: String
  working_time_nnull: String
  or: [ExperienceFilter]
  and: [ExperienceFilter]
}

type ExperienceItem {
  id: ID!
  company_name: String
  company_logo: DirectusFileItem
  position: String
  description: String
  website: String
  working_time: String
}

type Information {
  data: [InformationItem]
  meta: Metadata
}

input InformationFilter {
  id_eq: Int
  id_neq: Int
  id_lt: Int
  id_lte: Int
  id_gt: Int
  id_gte: Int
  id_in: String
  id_nin: String
  id_between: String
  id_nbetween: String
  created_on_eq: Datetime
  created_on_neq: Datetime
  created_on_lt: Datetime
  created_on_lte: Datetime
  created_on_gt: Datetime
  created_on_gte: Datetime
  created_on_in: Datetime
  created_on_nin: Datetime
  created_on_between: String
  created_on_nbetween: String
  text_eq: String
  text_neq: String
  text_contains: String
  text_ncontains: String
  text_rlike: String
  text_nrlike: String
  text_empty: String
  text_nempty: String
  text_null: String
  text_nnull: String
  icon_eq: String
  icon_neq: String
  icon_contains: String
  icon_ncontains: String
  icon_rlike: String
  icon_nrlike: String
  icon_empty: String
  icon_nempty: String
  icon_null: String
  icon_nnull: String
  or: [InformationFilter]
  and: [InformationFilter]
}

type InformationItem {
  id: ID!
  created_on: Datetime
  text: String!
  icon: String!
}

type Interests {
  data: [InterestsItem]
  meta: Metadata
}

input InterestsFilter {
  id_eq: Int
  id_neq: Int
  id_lt: Int
  id_lte: Int
  id_gt: Int
  id_gte: Int
  id_in: String
  id_nin: String
  id_between: String
  id_nbetween: String
  created_on_eq: Datetime
  created_on_neq: Datetime
  created_on_lt: Datetime
  created_on_lte: Datetime
  created_on_gt: Datetime
  created_on_gte: Datetime
  created_on_in: Datetime
  created_on_nin: Datetime
  created_on_between: String
  created_on_nbetween: String
  name_eq: String
  name_neq: String
  name_contains: String
  name_ncontains: String
  name_rlike: String
  name_nrlike: String
  name_empty: String
  name_nempty: String
  name_null: String
  name_nnull: String
  icon_eq: String
  icon_neq: String
  icon_contains: String
  icon_ncontains: String
  icon_rlike: String
  icon_nrlike: String
  icon_empty: String
  icon_nempty: String
  icon_null: String
  icon_nnull: String
  description_eq: String
  description_neq: String
  description_contains: String
  description_ncontains: String
  description_rlike: String
  description_nrlike: String
  description_empty: String
  description_nempty: String
  description_null: String
  description_nnull: String
  or: [InterestsFilter]
  and: [InterestsFilter]
}

type InterestsItem {
  id: ID!
  created_on: Datetime
  name: String!
  icon: String!
  description: String
}

"""
The `JSON` scalar type represents JSON values as specified by
        [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
"""
scalar JSON

type Main {
  data: [MainItem]
  meta: Metadata
}

input MainFilter {
  id_eq: Int
  id_neq: Int
  id_lt: Int
  id_lte: Int
  id_gt: Int
  id_gte: Int
  id_in: String
  id_nin: String
  id_between: String
  id_nbetween: String
  title_eq: String
  title_neq: String
  title_contains: String
  title_ncontains: String
  title_rlike: String
  title_nrlike: String
  title_empty: String
  title_nempty: String
  title_null: String
  title_nnull: String
  subtitle_eq: String
  subtitle_neq: String
  subtitle_contains: String
  subtitle_ncontains: String
  subtitle_rlike: String
  subtitle_nrlike: String
  subtitle_empty: String
  subtitle_nempty: String
  subtitle_null: String
  subtitle_nnull: String
  social_all: String
  social_has: String
  background_image_all: String
  background_image_has: String
  slogan_eq: String
  slogan_neq: String
  slogan_contains: String
  slogan_ncontains: String
  slogan_rlike: String
  slogan_nrlike: String
  slogan_empty: String
  slogan_nempty: String
  slogan_null: String
  slogan_nnull: String
  resume_all: String
  resume_has: String
  or: [MainFilter]
  and: [MainFilter]
}

type MainItem {
  id: ID!
  title: String!
  subtitle: String!
  social: JSON!
  background_image: DirectusFileItem
  slogan: String!
  resume: DirectusFileItem
}

type Metadata {
  collection: String
  type: String
  result_count: Int
  total_count: Int
}

interface Node {
  id: ID
}

type Query {
  directus_activity(id: Int, limit: Int, offset: Int, filter: DirectusActivityFilter): DirectusActivity
  directus_collections(name: String, limit: Int, offset: Int): DirectusCollection
  directus_collection_presets(id: ID, limit: Int, offset: Int, filter: DirectusCollectionPresetsFilter): DirectusCollectionPreset
  directus_fields(collection: String, field: String): DirectusField
  directus_files(id: ID, limit: Int, offset: Int, filter: DirectusFilesFilter): DirectusFile
  directus_folders(id: ID, limit: Int, offset: Int, filter: DirectusFoldersFilter): DirectusFolder
  directus_permissions(id: ID, limit: Int, offset: Int, filter: DirectusPermissionsFilter): DirectusPermission
  directus_relations(id: ID, limit: Int, offset: Int, filter: DirectusPermissionsFilter): DirectusRelation
  directus_revisions(id: ID, limit: Int, offset: Int): DirectusRevision
  directus_roles(id: ID, limit: Int, offset: Int): DirectusRole
  directus_settings(id: ID, limit: Int, offset: Int): DirectusSetting
  directus_users(id: ID, limit: Int, offset: Int, filter: DirectusUsersFilter): DirectusUser
  about_me(id: Int, limit: Int, offset: Int, lang: String, filter: AboutMeFilter): AboutMe
  carousel(id: Int, limit: Int, offset: Int, lang: String, filter: CarouselFilter): Carousel
  contact(id: Int, limit: Int, offset: Int, lang: String, filter: ContactFilter): Contact
  experience(id: Int, limit: Int, offset: Int, lang: String, filter: ExperienceFilter): Experience
  information(id: Int, limit: Int, offset: Int, lang: String, filter: InformationFilter): Information
  interests(id: Int, limit: Int, offset: Int, lang: String, filter: InterestsFilter): Interests
  main(id: Int, limit: Int, offset: Int, lang: String, filter: MainFilter): Main
  skills(id: Int, limit: Int, offset: Int, lang: String, filter: SkillsFilter): Skills
}

type Skills {
  data: [SkillsItem]
  meta: Metadata
}

input SkillsFilter {
  id_eq: Int
  id_neq: Int
  id_lt: Int
  id_lte: Int
  id_gt: Int
  id_gte: Int
  id_in: String
  id_nin: String
  id_between: String
  id_nbetween: String
  created_on_eq: Datetime
  created_on_neq: Datetime
  created_on_lt: Datetime
  created_on_lte: Datetime
  created_on_gt: Datetime
  created_on_gte: Datetime
  created_on_in: Datetime
  created_on_nin: Datetime
  created_on_between: String
  created_on_nbetween: String
  type_eq: String
  type_neq: String
  type_contains: String
  type_ncontains: String
  type_rlike: String
  type_nrlike: String
  type_empty: String
  type_nempty: String
  type_null: String
  type_nnull: String
  image_all: String
  image_has: String
  link_eq: String
  link_neq: String
  link_contains: String
  link_ncontains: String
  link_rlike: String
  link_nrlike: String
  link_empty: String
  link_nempty: String
  link_null: String
  link_nnull: String
  name_eq: String
  name_neq: String
  name_contains: String
  name_ncontains: String
  name_rlike: String
  name_nrlike: String
  name_empty: String
  name_nempty: String
  name_null: String
  name_nnull: String
  or: [SkillsFilter]
  and: [SkillsFilter]
}

type SkillsItem {
  id: ID!
  created_on: Datetime
  type: String!
  image: DirectusFileItem!
  link: String!
  name: String!
}

